//backend 

class Customer {
    constructor(id,firstName,lastName,email){
        this.id = id;
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }
    getFullName(){
        return
    }
    getShippingStreetAddress(){
        return 
    }
    getBillingPostalCode(){
        return 
    }
    getShippingPostalCode(){
        return
    }
    getShippingState(){
        return 
    }
    getFullAddressAsString(){
        return 
    }
    getFirstName(){
        return 
    }
    getLastName(){
        return
    }
    getRecentOrders(){
        return 
    }
    getLastOrder(){
        return 
    }
    getOrderByOrderID(){
        return 
    }
    createOrder(orderParams){
        return
    }
    updateBillingAddress(addressParams){
        return
    }
    signUpForNewsletter(){
        return 
    }
    submitCustomerFeedbackSurvey(surveyParams){
        return 
    }
    calculateCustomerValueToCompany(){
        return 
    }
    sendPromotionForProduct(){
        return
    }
    smarkAsAVeryImportantCustomer(){
        return 
    }
    getAllProductsEverPurchased(){
        return
    }
    getNumberOfAllProductsEverPurchased(){
        return 
    }
    getAllEmailsSentToCustomer(){
        return
    }
}
